apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-github-actions-artifactory-100625y
  janus-idp.io/tekton: python-github-actions-artifactory-100625y
  backstage.io/kubernetes-id: python-github-actions-artifactory-100625y
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: python-github-actions-artifactory-100625y
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
